// eslint.config.js
import js from '@eslint/js';
import prettier from 'eslint-config-prettier';

export default [
    js.configs.recommended,
    prettier,
    {
        files: ['js/**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                THREE: 'readonly',
                console: 'readonly',
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                performance: 'readonly',
                MutationObserver: 'readonly',
                IntersectionObserver: 'readonly',
                ResizeObserver: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                fetch: 'readonly',
                XMLHttpRequest: 'readonly',
                Promise: 'readonly',
                Math: 'readonly',
                JSON: 'readonly',
                Array: 'readonly',
                Object: 'readonly',
                String: 'readonly',
                Number: 'readonly',
                Boolean: 'readonly',
                Map: 'readonly',
                Set: 'readonly',
                Symbol: 'readonly',
                BigInt: 'readonly',
                parseInt: 'readonly',
                parseFloat: 'readonly',
                isNaN: 'readonly',
                isFinite: 'readonly',
                NaN: 'readonly',
                undefined: 'readonly',
                null: 'readonly',
                encodeURIComponent: 'readonly',
                decodeURIComponent: 'readonly',
                btoa: 'readonly',
                atob: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                AbortController: 'readonly',
                DOMException: 'readonly',
                CSS: 'readonly',
                sessionStorage: 'readonly',
                localStorage: 'readonly',
                requestIdleCallback: 'readonly',
                HTMLButtonElement: 'readonly',
                HTMLElement: 'readonly',
                Event: 'readonly',
                CustomEvent: 'readonly',
                MessageChannel: 'readonly',
                AbortSignal: 'readonly',
                location: 'readonly',
                history: 'readonly',
                ORBIT_MAX_DISTANCE_DEFAULT: 'readonly',
                ORBIT_ROTATE_SPEED_DEFAULT: 'readonly',
                ORBIT_PAN_SPEED_DEFAULT: 'readonly',
                SCENE_REVEAL_DURATION_MS: 'readonly'
            }
        },
        rules: {
            'no-unused-vars': 'warn',
            'no-undef': 'error',
            'no-console': ['error', { allow: ['warn', 'error'] }],
            'no-var': 'error',
            'eqeqeq': 'error',
            'no-empty': ['error', { allowEmptyCatch: true }],
            'no-useless-escape': 'error'
        }
    }
];
