export function resetRouteTraceDiagnostics() {}
export function removeRouteTraceOverlay() {}
export function setRouteChoreographyPhase() {}
export function refreshRouteTraceOverlay() {}
export function updateRouteTraceOverlayPositions() {}
export function refreshFocusSemanticOverlay() {}
export function updateFocusSemanticOverlayPositions() {}
export function removeFocusSemanticOverlay() {}
export function resetFocusThreadDiagnostics() {}
export function syncArrivalHandoffOverlay() {}
export function updateArrivalHandoffOverlay() {}
export function disposeArrivalHandoffOverlay() {}
